//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.Web.Models
{
    using System;
    
    public partial class getTopicById
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public int StatusID { get; set; }
        public string StatusName { get; set; }
        public Nullable<int> TotalItems { get; set; }
        public Nullable<int> TotalUnreadItems { get; set; }
        public string Summary { get; set; }
        public string DocumentID { get; set; }
        public string SpareField { get; set; }
        public string BugTicketId { get; set; }
    }
}
