//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forum.Web.Models
{
    using System;
    
    public partial class ListTopicUserAudit
    {
        public string UserName { get; set; }
        public Nullable<System.DateTime> LastViewed { get; set; }
    }
}
